services:
  server:
    image: andreysenov/firebase-tools:latest-alpine
    ports:
      - 5000:5000
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 300M

    command: firebase emulators:start -P $COMPOSE_PROJECT_NAME
    volumes:
      - ./firebase.json:/home/node/firebase.json
      - ./assets:/home/node/assets
