on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown
          components: clippy, rustfmt
      
      - run: cargo install wasm-pack --locked

      - run: make release -j 8

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ENKU }}"
          projectId: ${{secrets.FIREBASE_PROJECT}}
          channelId: live
