on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown,x86_64-unknown-linux-gnu
          components: clippy, rustfmt
      
      - run: cargo install wasm-bindgen-cli

      - run: make release

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ENKU }}"
          projectId: ${{secrets.FIREBASE_PROJECT}}
          channelId: live