on:
  pull_request:

jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown
          components: clippy, rustfmt
      
      - run: cargo install wasm-bindgen-cli

      - run: make release -j 8
      
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ENKU }}"
          expires: 7d
          projectId: ${{secrets.FIREBASE_PROJECT}}